name: Release

on:
  workflow_dispatch:
    inputs:
      ref:
        description: Commit to use for the release
        required: true

jobs:
  linux:
    # if: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}

    - name: Virtual env
      run: python3.12 -m venv .venv

    - name: Release
      run: |
        pip install maturin
        maturin build --release

    - name: Upload files
      uses: actions/upload-artifact@v4
      with:
        path: target/wheels/*.*

    # - name: Wait for ssh connection
    #   uses: owenthereal/action-upterm@v1
