name: Release

on:
  workflow_dispatch:
    inputs:
      ref:
        description: Commit to use for the release
        required: true
jobs:
  posix:
    strategy:
      matrix:
        # python: ["3.12", "3.14"]
        # os: [ubuntu-latest, macos-latest]
        python: ["3.14"]
        os: [macos-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Wait for ssh connection
        uses: owenthereal/action-upterm@v1

      - name: Virtual env
        run: python${{ matrix.python }} -m venv .venv

      - name: Release
        run: |
          source .venv/bin/activate
          pip install maturin
          maturin build --release

      - name: Upload files
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-py${{ matrix.python }}
          path: target/wheels/

      - name: Publish to PyPI
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.MATURIN_PYPI_TOKEN }}
        run: |
          source .venv/bin/activate
          maturin upload --non-interactive target/wheels/*.*
